name: "GPSD"
description: "Provide GPS data to Home Assistant."
version: "0.1.1"
slug: "gpsd"
init: false
arch:
  - aarch64
  - amd64
  - armv7
  - i386
ports:
  8123/tcp: 8123
options:
  gps_device: "/dev/ttyACM0"
schema:
  gps_device: "str"
volumes:
    - 'share:/share'
host_network: true
