name: "GPS Daemon"
description: "Provides GPS data to Home Assistant."
version: "0.1.4"
slug: "gpsd"
init: false
arch:
  - aarch64
  - amd64
  - armv7
  - i386
ports:
  2947/tcp: 2947
options:
    gps_device: "/dev/ttyACM0"
    gps_options: "-N -G -n"
schema:
    gps_device: "str"
    gps_options: "str"
devices:
    - /dev/ttyACM0:/dev/ttyACM0
    - /dev/ttyUSB0:/dev/ttyUSB0
    - /dev/ttyUSB0:/dev/ttyUSB1
volumes:
    - 'share:/share'
host_network: true
privileged: 
    - true
