name: "GPS Daemon"
description: "Provides GPS data to Home Assistant."
version: "0.1.21"
slug: "gpsd"
init: false
arch:
  - aarch64
  - amd64
  - armv7
  - i386

ports:
  2947/tcp: 2947

options:
    DEVICE: "/dev/ttyACM1"
    OPTIONS: "-b -N -G -n"

schema:
  DEVICE: "device"
  OPTIONS: "str"

devices:
    - /dev/ttyACM0:/dev/ttyACM0
    - /dev/ttyACM0:/dev/ttyACM1
    - /dev/ttyACM0:/dev/ttyAMA10
    - /dev/ttyUSB0:/dev/ttyUSB0
    - /dev/ttyUSB0:/dev/ttyUSB1

volumes:
    - 'share:/share'

host_network: true

privileged:
    - DAC_READ_SEARCH
#full_access: true
