name: "GPS Daemon"
description: "Provides GPS data to Home Assistant."
version: "0.1.11"
slug: "gpsd"
init: false
arch:
  - aarch64
  - amd64
  - armv7
  - i386
ports:
  2947/tcp: 2947
options:
    device: "/dev/ttyACM0"
    options: "-b -N -G -n"
schema:
    device: "str"
    options: "str"
devices:
    - /dev/ttyACM0:/dev/ttyACM0
    - /dev/ttyACM0:/dev/ttyAMA10
    - /dev/ttyUSB0:/dev/ttyUSB0
    - /dev/ttyUSB0:/dev/ttyUSB1
volumes:
    - 'share:/share'
host_network: true
full_access: true
