name: "GPS Daemon"
description: "Provides GPS data to Home Assistant."
version: "0.1.25"
slug: "gpsd"
init: false
boot: auto

arch:
  - aarch64
  - amd64
  - armv7
  - i386

ports:
  2947/tcp: 2947

options:
    device: "/dev/ttyACM1"
    options: "-b -N -G -n"

schema:
  tty_device:
    type: string
    default: "/dev/ACM0"
    selector:
      device:
        integration: "serial"
  options: "str"

devices:
    - /dev/ttyACM0:/dev/ttyACM0
    - /dev/ttyACM0:/dev/ttyACM1
    - /dev/ttyACM0:/dev/ttyAMA10
    - /dev/ttyUSB0:/dev/ttyUSB0
    - /dev/ttyUSB0:/dev/ttyUSB1

volumes:
    - /dev:/dev:rw
    - 'share:/share'

host_network: true

privileged:
    - DAC_READ_SEARCH
#full_access: true
